package Object;

import java.io.BufferedWriter;
import java.io.Closeable;
import java.io.FileWriter;
import java.io.IOException;

public class IOExample {
    public static void main(String[] args) {
        try(MyResource myResource = new MyResource()){
            myResource.writeToFile("C:\\testing\\sampleFile1.txt");
        }catch (IOException e){
            System.err.println("Exception.............");
        }

    }
}



class MyResource implements Closeable {

    @Override
    public void close() throws IOException {
        System.out.println("close");
    }

    public void writeToFile(String fileName) {
        String text = "\n" +
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n" +
                "<!-- NewPage -->\n" +
                "<html lang=\"en\">\n" +
                "<head>\n" +
                "<!-- Generated by javadoc (1.8.0_411) on Thu Apr 04 12:03:47 GMT 2024 -->\n" +
                "<title>java.io (Java Platform SE 8 )</title>\n" +
                "<meta name=\"date\" content=\"2024-04-04\">\n" +
                "<meta name=\"keywords\" content=\"java.io package\">\n" +
                "<link rel=\"stylesheet\" type=\"text/css\" href=\"../../stylesheet.css\" title=\"Style\">\n" +
                "<script type=\"text/javascript\" src=\"../../script.js\"></script>\n" +
                "<script>window.ohcglobal || document.write('<script src=\"/en/dcommon/js/global.js\">\\x3C/script>')</script></head>\n" +
                "<body>\n" +
                "<script type=\"text/javascript\"><!--\n" +
                "    try {\n" +
                "        if (location.href.indexOf('is-external=true') == -1) {\n" +
                "            parent.document.title=\"java.io (Java Platform SE 8 )\";\n" +
                "        }\n" +
                "    }\n" +
                "    catch(err) {\n" +
                "    }\n" +
                "//-->\n" +
                "</script>\n" +
                "<noscript>\n" +
                "<div>JavaScript is disabled on your browser.</div>\n" +
                "</noscript>\n" +
                "<!-- ========= START OF TOP NAVBAR ======= -->\n" +
                "<div class=\"topNav\"><a name=\"navbar.top\">\n" +
                "<!--   -->\n" +
                "</a>\n" +
                "<div class=\"skipNav\"><a href=\"#skip.navbar.top\" title=\"Skip navigation links\">Skip navigation links</a></div>\n" +
                "<a name=\"navbar.top.firstrow\">\n" +
                "<!--   -->\n" +
                "</a>\n" +
                "<ul class=\"navList\" title=\"Navigation\">\n" +
                "<li><a href=\"../../overview-summary.html\">Overview</a></li>\n" +
                "<li class=\"navBarCell1Rev\">Package</li>\n" +
                "<li>Class</li>\n" +
                "<li><a href=\"package-use.html\">Use</a></li>\n" +
                "<li><a href=\"package-tree.html\">Tree</a></li>\n" +
                "<li><a href=\"../../deprecated-list.html\">Deprecated</a></li>\n" +
                "<li><a href=\"../../index-files/index-1.html\">Index</a></li>\n" +
                "<li><a href=\"../../help-doc.html\">Help</a></li>\n" +
                "</ul>\n" +
                "<div class=\"aboutLanguage\"><strong>Java&trade;&nbsp;Platform<br>Standard&nbsp;Ed.&nbsp;8</strong></div>\n" +
                "</div>\n" +
                "<div class=\"subNav\">\n" +
                "<ul class=\"navList\">\n" +
                "<li><a href=\"../../java/beans/beancontext/package-summary.html\">Prev&nbsp;Package</a></li>\n" +
                "<li><a href=\"../../java/lang/package-summary.html\">Next&nbsp;Package</a></li>\n" +
                "</ul>\n" +
                "<ul class=\"navList\">\n" +
                "<li><a href=\"../../index.html?java/io/package-summary.html\" target=\"_top\">Frames</a></li>\n" +
                "<li><a href=\"package-summary.html\" target=\"_top\">No&nbsp;Frames</a></li>\n" +
                "</ul>\n" +
                "<ul class=\"navList\" id=\"allclasses_navbar_top\">\n" +
                "<li><a href=\"../../allclasses-noframe.html\">All&nbsp;Classes</a></li>\n" +
                "</ul>\n" +
                "<div>\n" +
                "<script type=\"text/javascript\"><!--\n" +
                "  allClassesLink = document.getElementById(\"allclasses_navbar_top\");\n" +
                "  if(window==top) {\n" +
                "    allClassesLink.style.display = \"block\";\n" +
                "  }\n" +
                "  else {\n" +
                "    allClassesLink.style.display = \"none\";\n" +
                "  }\n" +
                "  //-->\n" +
                "</script>\n" +
                "</div>\n" +
                "<a name=\"skip.navbar.top\">\n" +
                "<!--   -->\n" +
                "</a></div>\n" +
                "<!-- ========= END OF TOP NAVBAR ========= -->\n" +
                "<div class=\"header\">\n" +
                "<h1 title=\"Package\" class=\"title\">Package&nbsp;java.io</h1>\n" +
                "<div class=\"docSummary\">\n" +
                "<div class=\"block\">Provides for system input and output through data streams,\n" +
                "serialization and the file system.</div>\n" +
                "</div>\n" +
                "<p>See:&nbsp;<a href=\"#package.description\">Description</a></p>\n" +
                "</div>\n" +
                "<div class=\"contentContainer\">\n" +
                "<ul class=\"blockList\">\n" +
                "<li class=\"blockList\">\n" +
                "<table class=\"typeSummary\" border=\"0\" cellpadding=\"3\" cellspacing=\"0\" summary=\"Interface Summary table, listing interfaces, and an explanation\">\n" +
                "<caption><span>Interface Summary</span><span class=\"tabEnd\">&nbsp;</span></caption>\n" +
                "<tr>\n" +
                "<th class=\"colFirst\" scope=\"col\">Interface</th>\n" +
                "<th class=\"colLast\" scope=\"col\">Description</th>\n" +
                "</tr>\n" +
                "<tbody>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/Closeable.html\" title=\"interface in java.io\">Closeable</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>Closeable</code> is a source or destination of data that can be closed.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/DataInput.html\" title=\"interface in java.io\">DataInput</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">The <code>DataInput</code> interface provides\n" +
                " for reading bytes from a binary stream and\n" +
                " reconstructing from them data in any of\n" +
                " the Java primitive types.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/DataOutput.html\" title=\"interface in java.io\">DataOutput</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">The <code>DataOutput</code> interface provides\n" +
                " for converting data from any of the Java\n" +
                " primitive types to a series of bytes and\n" +
                " writing these bytes to a binary stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/Externalizable.html\" title=\"interface in java.io\">Externalizable</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Only the identity of the class of an Externalizable instance is\n" +
                " written in the serialization stream and it is the responsibility\n" +
                " of the class to save and restore the contents of its instances.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FileFilter.html\" title=\"interface in java.io\">FileFilter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A filter for abstract pathnames.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FilenameFilter.html\" title=\"interface in java.io\">FilenameFilter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Instances of classes that implement this interface are used to\n" +
                " filter filenames.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/Flushable.html\" title=\"interface in java.io\">Flushable</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <tt>Flushable</tt> is a destination of data that can be flushed.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectInput.html\" title=\"interface in java.io\">ObjectInput</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">ObjectInput extends the DataInput interface to include the reading of\n" +
                " objects.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectInputValidation.html\" title=\"interface in java.io\">ObjectInputValidation</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Callback interface to allow validation of objects within a graph.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectOutput.html\" title=\"interface in java.io\">ObjectOutput</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">ObjectOutput extends the DataOutput interface to include writing of objects.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectStreamConstants.html\" title=\"interface in java.io\">ObjectStreamConstants</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Constants written into the Object Serialization Stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/Serializable.html\" title=\"interface in java.io\">Serializable</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Serializability of a class is enabled by the class implementing the\n" +
                " java.io.Serializable interface.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "</tbody>\n" +
                "</table>\n" +
                "</li>\n" +
                "<li class=\"blockList\">\n" +
                "<table class=\"typeSummary\" border=\"0\" cellpadding=\"3\" cellspacing=\"0\" summary=\"Class Summary table, listing classes, and an explanation\">\n" +
                "<caption><span>Class Summary</span><span class=\"tabEnd\">&nbsp;</span></caption>\n" +
                "<tr>\n" +
                "<th class=\"colFirst\" scope=\"col\">Class</th>\n" +
                "<th class=\"colLast\" scope=\"col\">Description</th>\n" +
                "</tr>\n" +
                "<tbody>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/BufferedInputStream.html\" title=\"class in java.io\">BufferedInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>BufferedInputStream</code> adds\n" +
                " functionality to another input stream-namely,\n" +
                " the ability to buffer the input and to\n" +
                " support the <code>mark</code> and <code>reset</code>\n" +
                " methods.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/BufferedOutputStream.html\" title=\"class in java.io\">BufferedOutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">The class implements a buffered output stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/BufferedReader.html\" title=\"class in java.io\">BufferedReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Reads text from a character-input stream, buffering characters so as to\n" +
                " provide for the efficient reading of characters, arrays, and lines.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/BufferedWriter.html\" title=\"class in java.io\">BufferedWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Writes text to a character-output stream, buffering characters so as to\n" +
                " provide for the efficient writing of single characters, arrays, and strings.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ByteArrayInputStream.html\" title=\"class in java.io\">ByteArrayInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>ByteArrayInputStream</code> contains\n" +
                " an internal buffer that contains bytes that\n" +
                " may be read from the stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ByteArrayOutputStream.html\" title=\"class in java.io\">ByteArrayOutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This class implements an output stream in which the data is\n" +
                " written into a byte array.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/CharArrayReader.html\" title=\"class in java.io\">CharArrayReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This class implements a character buffer that can be used as a\n" +
                " character-input stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/CharArrayWriter.html\" title=\"class in java.io\">CharArrayWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This class implements a character buffer that can be used as an Writer.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/Console.html\" title=\"class in java.io\">Console</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Methods to access the character-based console device, if any, associated\n" +
                " with the current Java virtual machine.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/DataInputStream.html\" title=\"class in java.io\">DataInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A data input stream lets an application read primitive Java data\n" +
                " types from an underlying input stream in a machine-independent\n" +
                " way.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/DataOutputStream.html\" title=\"class in java.io\">DataOutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A data output stream lets an application write primitive Java data\n" +
                " types to an output stream in a portable way.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/File.html\" title=\"class in java.io\">File</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">An abstract representation of file and directory pathnames.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FileDescriptor.html\" title=\"class in java.io\">FileDescriptor</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Instances of the file descriptor class serve as an opaque handle\n" +
                " to the underlying machine-specific structure representing an open\n" +
                " file, an open socket, or another source or sink of bytes.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FileInputStream.html\" title=\"class in java.io\">FileInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>FileInputStream</code> obtains input bytes\n" +
                " from a file in a file system.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FileOutputStream.html\" title=\"class in java.io\">FileOutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A file output stream is an output stream for writing data to a\n" +
                " <code>File</code> or to a <code>FileDescriptor</code>.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FilePermission.html\" title=\"class in java.io\">FilePermission</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This class represents access to a file or directory.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FileReader.html\" title=\"class in java.io\">FileReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Convenience class for reading character files.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FileWriter.html\" title=\"class in java.io\">FileWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Convenience class for writing character files.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FilterInputStream.html\" title=\"class in java.io\">FilterInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>FilterInputStream</code> contains\n" +
                " some other input stream, which it uses as\n" +
                " its  basic source of data, possibly transforming\n" +
                " the data along the way or providing  additional\n" +
                " functionality.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FilterOutputStream.html\" title=\"class in java.io\">FilterOutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This class is the superclass of all classes that filter output\n" +
                " streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FilterReader.html\" title=\"class in java.io\">FilterReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Abstract class for reading filtered character streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FilterWriter.html\" title=\"class in java.io\">FilterWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Abstract class for writing filtered character streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/InputStream.html\" title=\"class in java.io\">InputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This abstract class is the superclass of all classes representing\n" +
                " an input stream of bytes.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/InputStreamReader.html\" title=\"class in java.io\">InputStreamReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">An InputStreamReader is a bridge from byte streams to character streams: It\n" +
                " reads bytes and decodes them into characters using a specified <a href=\"../../java/nio/charset/Charset.html\" title=\"class in java.nio.charset\"><code>charset</code></a>.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/LineNumberInputStream.html\" title=\"class in java.io\">LineNumberInputStream</a></td>\n" +
                "<td class=\"colLast\">Deprecated\n" +
                "<div class=\"block\"><span class=\"deprecationComment\">This class incorrectly assumes that bytes adequately represent\n" +
                "             characters.</span></div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/LineNumberReader.html\" title=\"class in java.io\">LineNumberReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A buffered character-input stream that keeps track of line numbers.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectInputStream.html\" title=\"class in java.io\">ObjectInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">An ObjectInputStream deserializes primitive data and objects previously\n" +
                " written using an ObjectOutputStream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectInputStream.GetField.html\" title=\"class in java.io\">ObjectInputStream.GetField</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Provide access to the persistent fields read from the input stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectOutputStream.html\" title=\"class in java.io\">ObjectOutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">An ObjectOutputStream writes primitive data types and graphs of Java objects\n" +
                " to an OutputStream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectOutputStream.PutField.html\" title=\"class in java.io\">ObjectOutputStream.PutField</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Provide programmatic access to the persistent fields to be written\n" +
                " to ObjectOutput.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectStreamClass.html\" title=\"class in java.io\">ObjectStreamClass</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Serialization's descriptor for classes.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectStreamField.html\" title=\"class in java.io\">ObjectStreamField</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A description of a Serializable field from a Serializable class.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/OutputStream.html\" title=\"class in java.io\">OutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This abstract class is the superclass of all classes representing\n" +
                " an output stream of bytes.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/OutputStreamWriter.html\" title=\"class in java.io\">OutputStreamWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">An OutputStreamWriter is a bridge from character streams to byte streams:\n" +
                " Characters written to it are encoded into bytes using a specified <a href=\"../../java/nio/charset/Charset.html\" title=\"class in java.nio.charset\"><code>charset</code></a>.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PipedInputStream.html\" title=\"class in java.io\">PipedInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A piped input stream should be connected\n" +
                " to a piped output stream; the piped  input\n" +
                " stream then provides whatever data bytes\n" +
                " are written to the piped output  stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PipedOutputStream.html\" title=\"class in java.io\">PipedOutputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A piped output stream can be connected to a piped input stream\n" +
                " to create a communications pipe.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PipedReader.html\" title=\"class in java.io\">PipedReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Piped character-input streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PipedWriter.html\" title=\"class in java.io\">PipedWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Piped character-output streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PrintStream.html\" title=\"class in java.io\">PrintStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>PrintStream</code> adds functionality to another output stream,\n" +
                " namely the ability to print representations of various data values\n" +
                " conveniently.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PrintWriter.html\" title=\"class in java.io\">PrintWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Prints formatted representations of objects to a text-output stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PushbackInputStream.html\" title=\"class in java.io\">PushbackInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>PushbackInputStream</code> adds\n" +
                " functionality to another input stream, namely\n" +
                " the  ability to \"push back\" or \"unread\"\n" +
                " one byte.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/PushbackReader.html\" title=\"class in java.io\">PushbackReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A character-stream reader that allows characters to be pushed back into the\n" +
                " stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/RandomAccessFile.html\" title=\"class in java.io\">RandomAccessFile</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Instances of this class support both reading and writing to a\n" +
                " random access file.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/Reader.html\" title=\"class in java.io\">Reader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Abstract class for reading character streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/SequenceInputStream.html\" title=\"class in java.io\">SequenceInputStream</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A <code>SequenceInputStream</code> represents\n" +
                " the logical concatenation of other input\n" +
                " streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/SerializablePermission.html\" title=\"class in java.io\">SerializablePermission</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">This class is for Serializable permissions.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/StreamTokenizer.html\" title=\"class in java.io\">StreamTokenizer</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">The <code>StreamTokenizer</code> class takes an input stream and\n" +
                " parses it into \"tokens\", allowing the tokens to be\n" +
                " read one at a time.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/StringBufferInputStream.html\" title=\"class in java.io\">StringBufferInputStream</a></td>\n" +
                "<td class=\"colLast\">Deprecated\n" +
                "<div class=\"block\"><span class=\"deprecationComment\">This class does not properly convert characters into bytes.</span></div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/StringReader.html\" title=\"class in java.io\">StringReader</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A character stream whose source is a string.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/StringWriter.html\" title=\"class in java.io\">StringWriter</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">A character stream that collects its output in a string buffer, which can\n" +
                " then be used to construct a string.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/Writer.html\" title=\"class in java.io\">Writer</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Abstract class for writing to character streams.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "</tbody>\n" +
                "</table>\n" +
                "</li>\n" +
                "<li class=\"blockList\">\n" +
                "<table class=\"typeSummary\" border=\"0\" cellpadding=\"3\" cellspacing=\"0\" summary=\"Exception Summary table, listing exceptions, and an explanation\">\n" +
                "<caption><span>Exception Summary</span><span class=\"tabEnd\">&nbsp;</span></caption>\n" +
                "<tr>\n" +
                "<th class=\"colFirst\" scope=\"col\">Exception</th>\n" +
                "<th class=\"colLast\" scope=\"col\">Description</th>\n" +
                "</tr>\n" +
                "<tbody>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/CharConversionException.html\" title=\"class in java.io\">CharConversionException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Base class for character conversion exceptions.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/EOFException.html\" title=\"class in java.io\">EOFException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Signals that an end of file or end of stream has been reached\n" +
                " unexpectedly during input.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/FileNotFoundException.html\" title=\"class in java.io\">FileNotFoundException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Signals that an attempt to open the file denoted by a specified pathname\n" +
                " has failed.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/InterruptedIOException.html\" title=\"class in java.io\">InterruptedIOException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Signals that an I/O operation has been interrupted.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/InvalidClassException.html\" title=\"class in java.io\">InvalidClassException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Thrown when the Serialization runtime detects one of the following\n" +
                " problems with a Class.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/InvalidObjectException.html\" title=\"class in java.io\">InvalidObjectException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Indicates that one or more deserialized objects failed validation\n" +
                " tests.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/IOException.html\" title=\"class in java.io\">IOException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Signals that an I/O exception of some sort has occurred.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/NotActiveException.html\" title=\"class in java.io\">NotActiveException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Thrown when serialization or deserialization is not active.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/NotSerializableException.html\" title=\"class in java.io\">NotSerializableException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Thrown when an instance is required to have a Serializable interface.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/ObjectStreamException.html\" title=\"class in java.io\">ObjectStreamException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Superclass of all exceptions specific to Object Stream classes.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/OptionalDataException.html\" title=\"class in java.io\">OptionalDataException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Exception indicating the failure of an object read operation due to\n" +
                " unread primitive data, or the end of data belonging to a serialized\n" +
                " object in the stream.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/StreamCorruptedException.html\" title=\"class in java.io\">StreamCorruptedException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Thrown when control information that was read from an object stream\n" +
                " violates internal consistency checks.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/SyncFailedException.html\" title=\"class in java.io\">SyncFailedException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Signals that a sync operation has failed.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/UncheckedIOException.html\" title=\"class in java.io\">UncheckedIOException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Wraps an <a href=\"../../java/io/IOException.html\" title=\"class in java.io\"><code>IOException</code></a> with an unchecked exception.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/UnsupportedEncodingException.html\" title=\"class in java.io\">UnsupportedEncodingException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">The Character Encoding is not supported.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"rowColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/UTFDataFormatException.html\" title=\"class in java.io\">UTFDataFormatException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Signals that a malformed string in\n" +
                " <a href=\"DataInput.html#modified-utf-8\">modified UTF-8</a>\n" +
                " format has been read in a data\n" +
                " input stream or by any class that implements the data input\n" +
                " interface.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/WriteAbortedException.html\" title=\"class in java.io\">WriteAbortedException</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Signals that one of the ObjectStreamExceptions was thrown during a\n" +
                " write operation.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "</tbody>\n" +
                "</table>\n" +
                "</li>\n" +
                "<li class=\"blockList\">\n" +
                "<table class=\"typeSummary\" border=\"0\" cellpadding=\"3\" cellspacing=\"0\" summary=\"Error Summary table, listing errors, and an explanation\">\n" +
                "<caption><span>Error Summary</span><span class=\"tabEnd\">&nbsp;</span></caption>\n" +
                "<tr>\n" +
                "<th class=\"colFirst\" scope=\"col\">Error</th>\n" +
                "<th class=\"colLast\" scope=\"col\">Description</th>\n" +
                "</tr>\n" +
                "<tbody>\n" +
                "<tr class=\"altColor\">\n" +
                "<td class=\"colFirst\"><a href=\"../../java/io/IOError.html\" title=\"class in java.io\">IOError</a></td>\n" +
                "<td class=\"colLast\">\n" +
                "<div class=\"block\">Thrown when a serious I/O error has occurred.</div>\n" +
                "</td>\n" +
                "</tr>\n" +
                "</tbody>\n" +
                "</table>\n" +
                "</li>\n" +
                "</ul>\n" +
                "<a name=\"package.description\">\n" +
                "<!--   -->\n" +
                "</a>\n" +
                "<h2 title=\"Package java.io Description\">Package java.io Description</h2>\n" +
                "<div class=\"block\">Provides for system input and output through data streams,\n" +
                "serialization and the file system.\n" +
                "\n" +
                "Unless otherwise noted, passing a null argument to a constructor\n" +
                "or method in any class or interface in this package will cause a\n" +
                "<tt>NullPointerException</tt> to be thrown.\n" +
                "\n" +
                "<h2>Package Specification</h2>\n" +
                "<ul>\n" +
                "  <li><a href=\"../../../platform/serialization/spec/serialTOC.html\"> Java Object Serialization Specification </a>\n" +
                "</ul>\n" +
                "\n" +
                "<h2>Related Documentation</h2>\n" +
                "\n" +
                "For overviews, tutorials, examples, guides, and tool documentation,\n" +
                "please see:\n" +
                "<ul>\n" +
                "  <li><a href=\"../../../technotes/guides/serialization\">Serialization Enhancements</a>\n" +
                "</ul></div>\n" +
                "<dl>\n" +
                "<dt><span class=\"simpleTagLabel\">Since:</span></dt>\n" +
                "<dd>JDK1.0</dd>\n" +
                "</dl>\n" +
                "</div>\n" +
                "<!-- ======= START OF BOTTOM NAVBAR ====== -->\n" +
                "<div class=\"bottomNav\"><a name=\"navbar.bottom\">\n" +
                "<!--   -->\n" +
                "</a>\n" +
                "<div class=\"skipNav\"><a href=\"#skip.navbar.bottom\" title=\"Skip navigation links\">Skip navigation links</a></div>\n" +
                "<a name=\"navbar.bottom.firstrow\">\n" +
                "<!--   -->\n" +
                "</a>\n" +
                "<ul class=\"navList\" title=\"Navigation\">\n" +
                "<li><a href=\"../../overview-summary.html\">Overview</a></li>\n" +
                "<li class=\"navBarCell1Rev\">Package</li>\n" +
                "<li>Class</li>\n" +
                "<li><a href=\"package-use.html\">Use</a></li>\n" +
                "<li><a href=\"package-tree.html\">Tree</a></li>\n" +
                "<li><a href=\"../../deprecated-list.html\">Deprecated</a></li>\n" +
                "<li><a href=\"../../index-files/index-1.html\">Index</a></li>\n" +
                "<li><a href=\"../../help-doc.html\">Help</a></li>\n" +
                "</ul>\n" +
                "<div class=\"aboutLanguage\"><strong>Java&trade;&nbsp;Platform<br>Standard&nbsp;Ed.&nbsp;8</strong></div>\n" +
                "</div>\n" +
                "<div class=\"subNav\">\n" +
                "<ul class=\"navList\">\n" +
                "<li><a href=\"../../java/beans/beancontext/package-summary.html\">Prev&nbsp;Package</a></li>\n" +
                "<li><a href=\"../../java/lang/package-summary.html\">Next&nbsp;Package</a></li>\n" +
                "</ul>\n" +
                "<ul class=\"navList\">\n" +
                "<li><a href=\"../../index.html?java/io/package-summary.html\" target=\"_top\">Frames</a></li>\n" +
                "<li><a href=\"package-summary.html\" target=\"_top\">No&nbsp;Frames</a></li>\n" +
                "</ul>\n" +
                "<ul class=\"navList\" id=\"allclasses_navbar_bottom\">\n" +
                "<li><a href=\"../../allclasses-noframe.html\">All&nbsp;Classes</a></li>\n" +
                "</ul>\n" +
                "<div>\n" +
                "<script type=\"text/javascript\"><!--\n" +
                "  allClassesLink = document.getElementById(\"allclasses_navbar_bottom\");\n" +
                "  if(window==top) {\n" +
                "    allClassesLink.style.display = \"block\";\n" +
                "  }\n" +
                "  else {\n" +
                "    allClassesLink.style.display = \"none\";\n" +
                "  }\n" +
                "  //-->\n" +
                "</script>\n" +
                "</div>\n" +
                "<a name=\"skip.navbar.bottom\">\n" +
                "<!--   -->\n" +
                "</a></div>\n" +
                "<!-- ======== END OF BOTTOM NAVBAR ======= -->\n" +
                "<p class=\"legalCopy\"><small><font size=\"-1\"> <a href=\"http://bugreport.sun.com/bugreport/\">Submit a bug or feature</a> <br>For further API reference and developer documentation, see <a href=\"https://docs.oracle.com/javase/8/docs/index.html\" target=\"_blank\">Java SE Documentation</a>. That documentation contains more detailed, developer-targeted descriptions, with conceptual overviews, definitions of terms, workarounds, and working code examples.<br> <a href=\"../../../legal/cpyr.html\">Copyright</a> &#x00a9; 1993, 2024, Oracle and/or its affiliates.  All rights reserved. Use is subject to <a href=\"http://download.oracle.com/otndocs/jcp/java_se-8-mrel-spec/license.html\">license terms</a>. Also see the <a target=\"_blank\" href=\"http://www.oracle.com/technetwork/java/redist-137594.html\">documentation redistribution policy</a>. </font></small></p>\n" +
                "<!-- Start SiteCatalyst code   -->\n" +
                "<script type=\"application/javascript\" src=\"https://www.oracleimg.com/us/assets/metrics/ora_docs.js\"></script>\n" +
                "<!-- End SiteCatalyst code -->\n" +
                "<noscript>\n" +
                "<p>Scripting on this page tracks web page traffic, but does not change the content in any way.</p>\n" +
                "</noscript>\n" +
                "</body>\n" +
                "</html>\n";
        try(BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))){
          writer.write(text);
        }catch (IOException e){
            System.out.println("Exception.............");
        }
    }
}
